Repository sharetribe/ftw-hourly, pull requests merged in 2019-11, with the labels that each got.

#32 Move isDayBlocked prop to FieldDateAndTimeInput
  CHANGELOG.md
  src/components/FieldDateInput/DateInput.js
  src/components/FieldDateInput/FieldDateInput.example.js
  src/components/FieldDateInput/FieldDateInput.js
  src/forms/BookingTimeForm/FieldDateAndTimeInput.js
  src/util/dates.js
Labels: Review OK

#33 Fix issues when availability is until midnight
  CHANGELOG.md
  src/forms/BookingTimeForm/FieldDateAndTimeInput.js
  src/util/dates.js
Labels: Review wanted

#34 Hide the end date field from FieldDateAndTimeInput
  CHANGELOG.md
  src/forms/BookingTimeForm/FieldDateAndTimeInput.css
  src/forms/BookingTimeForm/FieldDateAndTimeInput.js
  src/translations/en.json
Labels: Review wanted

#35 Edit default locations
  CHANGELOG.md
  src/components/Footer/Footer.js
  src/default-location-searches.js
  src/translations/en.json
Labels: Review wanted

#37 Hide inbox tabs if user doesn't have a listing
  CHANGELOG.md
  src/containers/InboxPage/InboxPage.css
  src/containers/InboxPage/InboxPage.js
  src/containers/InboxPage/InboxPage.test.js
  src/containers/InboxPage/__snapshots__/InboxPage.test.js.snap
  src/translations/en.json
Labels: Review OK

#38 Fix same day detection
  CHANGELOG.md
  src/components/BookingTimeInfo/BookingTimeInfo.example.js
  src/components/TimeRange/TimeRange.js
  src/containers/InboxPage/__snapshots__/InboxPage.test.js.snap
  src/util/dates.js
  src/util/dates.test.js
Labels: Review OK

#39 Fix random prop types
  CHANGELOG.md
  src/components/FieldDateInput/FieldDateInput.js
  src/forms/BookingTimeForm/FieldDateAndTimeInput.js
Labels: Review OK

#43 Remove listings section from profile page
  CHANGELOG.md
  src/containers/ProfilePage/ProfilePage.js
Labels: Review OK

#41 Fix the listing link in Topbar
  CHANGELOG.md
  src/components/Topbar/Topbar.js
  src/components/TopbarDesktop/TopbarDesktop.js
  src/components/TopbarDesktop/__snapshots__/TopbarDesktop.test.js.snap
  src/containers/TopbarContainer/TopbarContainer.js
  src/ducks/user.duck.js
Labels: Review OK, Review comments

#44 Edit search page filters and listing's public data
  CHANGELOG.md
  src/components/EditListingDescriptionPanel/EditListingDescriptionPanel.js
  src/components/EditListingFeaturesPanel/EditListingFeaturesPanel.js
  src/components/EditListingWizard/EditListingWizard.js
  src/components/FieldCheckboxGroup/FieldCheckboxGroup.example.js
  src/components/ListingCard/ListingCard.css
  src/components/ListingCard/ListingCard.js
  src/components/ListingCard/__snapshots__/ListingCard.test.js.snap
  src/components/PropertyGroup/PropertyGroup.example.js
  src/components/SearchFilters/SearchFilters.js
  src/components/SearchFiltersMobile/SearchFiltersMobile.js
  src/components/SelectMultipleFilter/SelectMultipleFilter.example.js
  src/containers/ListingPage/ListingPage.js
  src/containers/ListingPage/ListingPage.test.js
  src/containers/ListingPage/SectionFeaturesMaybe.js
  src/containers/ListingPage/SectionHeading.js
  src/containers/ListingPage/__snapshots__/ListingPage.test.js.snap
  src/containers/SearchPage/README.md
  src/containers/SearchPage/SearchPage.helpers.test.js
  src/containers/SearchPage/SearchPage.js
  src/containers/SearchPage/SearchPage.test.js
  src/containers/SearchPage/__snapshots__/SearchPage.test.js.snap
  src/forms/EditListingDescriptionForm/CustomCategorySelectFieldMaybe.js
  src/forms/EditListingDescriptionForm/CustomCertificateSelectFieldMaybe.js
  src/forms/EditListingDescriptionForm/EditListingDescriptionForm.css
  src/forms/EditListingDescriptionForm/EditListingDescriptionForm.js
  src/forms/EditListingDescriptionForm/EditListingDescriptionForm.test.js
  src/forms/EditListingDescriptionForm/__snapshots__/EditListingDescriptionForm.test.js.snap
  src/forms/EditListingFeaturesForm/EditListingFeaturesForm.example.js
  src/forms/EditListingFeaturesForm/EditListingFeaturesForm.js
  src/marketplace-custom-config.js
  src/translations/en.json
Labels: Review wanted

#42 Change images
  CHANGELOG.md
  public/static/icons/android-chrome-192x192.png
  public/static/icons/android-chrome-384x384.png
  public/static/icons/android-chrome-512x512.png
  public/static/icons/apple-touch-icon.png
  public/static/icons/browserconfig.xml
  public/static/icons/favicon-16x16.png
  public/static/icons/favicon-32x32.png
  public/static/icons/favicon.ico
  public/static/icons/map-marker-32x32.png
  public/static/icons/mstile-150x150.png
  public/static/icons/safari-pinned-tab.svg
  src/assets/background-1440.jpg
  src/assets/saunatimeFacebook-1200x630.jpg
  src/assets/saunatimeTwitter-600x314.jpg
  src/assets/yogatimeFacebook-1200x630.jpg
  src/assets/yogatimeTwitter-600x314.jpg
  src/components/OwnListingLink/OwnListingLink.css
  src/components/OwnListingLink/OwnListingLink.js
  src/components/Page/Page.js
  src/components/SectionHero/SectionHero.js
  src/components/SectionHero/__snapshots__/SectionHero.test.js.snap
  src/components/SectionHowItWorks/SectionHowItWorks.js
  src/components/SectionLocations/SectionLocations.js
  src/components/SectionLocations/images/la-yogi.jpg
  src/components/SectionLocations/images/location_helsinki.jpg
  src/components/SectionLocations/images/location_rovaniemi.jpg
  src/components/SectionLocations/images/location_ruka.jpg
  src/components/SectionLocations/images/ny-yogi.jpg
  src/components/SectionLocations/images/sf-yogi.jpg
  src/components/Topbar/Topbar.js
  src/components/TopbarDesktop/TopbarDesktop.js
  src/components/TopbarDesktop/__snapshots__/TopbarDesktop.test.js.snap
  src/components/TopbarMobileMenu/TopbarMobileMenu.js
  src/containers/LandingPage/LandingPage.js
  src/containers/LandingPage/__snapshots__/LandingPage.test.js.snap
  src/marketplace.css
  src/translations/en.json
Labels: Review comments

#48 Fix example process email templates date formatting
  CHANGELOG.md
  ext/transaction-process/templates/booking-request-accepted/booking-request-accepted-html.html
  ext/transaction-process/templates/booking-request-auto-declined/booking-request-auto-declined-html.html
  ext/transaction-process/templates/booking-request-declined/booking-request-declined-html.html
  ext/transaction-process/templates/money-paid/money-paid-html.html
  ext/transaction-process/templates/new-booking-request/new-booking-request-html.html
Labels: Review OK, Review comments

#45 AvailabilityExceptions: list, delete and add
  src/components/EditListingAvailabilityPanel/EditListingAvailabilityPanel.css
  src/components/EditListingAvailabilityPanel/EditListingAvailabilityPanel.js
  src/components/EditListingWizard/EditListingWizardTab.js
  src/components/Footer/Footer.css
  src/components/IconEdit/IconEdit.css
  src/components/IconEdit/IconEdit.js
  src/containers/EditListingPage/EditListingPage.duck.js
  src/containers/EditListingPage/EditListingPage.js
  src/containers/EditListingPage/EditListingPage.test.js
  src/containers/EditListingPage/__snapshots__/EditListingPage.test.js.snap
  src/examples.js
  src/forms/EditListingAvailabilityExceptionForm/EditListingAvailabilityExceptionForm.css
  src/forms/EditListingAvailabilityExceptionForm/EditListingAvailabilityExceptionForm.example.js
  src/forms/EditListingAvailabilityExceptionForm/EditListingAvailabilityExceptionForm.js
  src/forms/index.js
  src/translations/en.json
Labels: Review comments

#47 Edit things related to showing order details
  src/components/ActivityFeed/ActivityFeed.js
  src/components/ActivityFeed/__snapshots__/ActivityFeed.test.js.snap
  src/components/Reviews/Reviews.js
  src/components/TransactionPanel/DetailCardImage.js
  src/components/TransactionPanel/TransactionPanel.js
  src/components/TransactionPanel/__snapshots__/TransactionPanel.test.js.snap
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/containers/InboxPage/InboxPage.js
  src/translations/en.json
Labels: Review wanted
